version: '3.7'

services:
  ui:
    # image: ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"